services:

    backend:
        build: ./backend
        ports:
            - "5000:5000"
        env_file:
            - ./.env

    school-frontend:
        build: ./frontend_school
        ports:
            - "3000:3000"
        depends_on:
            - backend
        stdin_open: true
        tty: true

    farmer-frontend:
        build: ./frontend_farmer
        ports:
            - "3001:3000"
        depends_on:
            - backend
        stdin_open: true
        tty: true
        
    ngrok:
        image: ngrok/ngrok:latest
        command: http backend:5000
        environment:
            NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
        depends_on:
            - backend
